#' Plot PCA Rotation
#'
#' Plot the features from a PCA rotation in a 2-dimensional scatter plot.
#' __Note:__ The precedence for the ordering of the coloring is as follows:
#'   \enumerate{
#'     \item{`col`}
#'     \item{`scores`}
#'   }
#'
#' @family PCA plots
#' @inheritParams plotPCAdims
#' @param aptamers Optional. A vector of `SeqIds` to mark on the plot. Typically
#'   a vector of analytes related to sample handling, or of other clinical
#'   relevance. Marked with a hollow diamond (see [pch()]).
#' @param aptamers2 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   triangle (see [pch()]).
#' @param aptamers3 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   square (see [pch()]).
#' @param aptamers4 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   circle (see [pch()]).
#' @param aptamers5 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   upside-down triangle (see [pch()]).
#' @param classes Optional. A vector indicating the classes of features used for
#'   coloring the points. Must be the same length as the number of features.
#' @param auto.ident Logical. Should the top 10 features, in both dimensions,
#'   be identified and labeled on the plot?
#' @param lab.cex Numeric. Font size of the point labels generated by `auto.ident`.
#'   `auto.ident` must be TRUE.
#' @param ... Additional arguments passed to [plotPCAdims()].
#' @author Michael Mehan
#' @examples
#' pca <- center_scale(log10(sim_test_data), center = TRUE, scale = FALSE) |>
#'   strip_meta() |>
#'   prcomp2()
#' plotRotation(pca, col = "green")
#'
#' class <- withr::with_seed(123, sample(sim_test_data$class_response, 40L))
#' plotRotation(pca, classes = class)
#'
#' apts <- withr::with_seed(123, sample(pcapkg:::getAnalytes(sim_test_data), 10L))
#' plotRotation(pca, aptamers = apts)
#' @importFrom ggplot2 geom_text aes
#' @export
plotRotation <- function(data.prcomp, dims = 1:2L,
                         classes = NULL, scores = NULL, col = NULL,
                         aptamers = NULL, aptamers2 = NULL, aptamers3 = NULL,
                         aptamers4 = NULL, aptamers5 = NULL,
                         lab.cex = 3, pt.cex = 2.5, auto.ident = TRUE, ...) {

  if ( !is.null(aptamers) ) {
    apMap <- mapAptCharacters(rownames(data.prcomp$rotation), aptamers,
                              aptamers2, aptamers3, aptamers4,
                              aptamers5, default.cex = pt.cex)
    pt.pch <- apMap$pch
    pt.cex <- apMap$cex
  } else {
    pt.pch <- 19
  }

  p <- plotPCAdims(data.prcomp, dims = dims, value = "rotation",
                   classes = classes, scores = scores, col = col,
                   pt.cex = pt.cex, pt.pch = pt.pch, ...)

  if ( auto.ident ) {
    rn1 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[1L]]), ])
    rn2 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[2L]]), ])
    p1  <- c(head(rn1, 5L), utils::tail(rn1, 5L))
    p2  <- c(head(rn2, 5L), utils::tail(rn2, 5L))
    top <- union(p1, p2)

    # Create data subset for labeling points identified in 'top'
    labs <- p$data[top, ]
    labs$label <- ifelse(rownames(labs) %in% top, getSeqId(top), "")

    p <- p + geom_text(data = labs, aes(x = x, y = y, label = label),
                       hjust = -0.20, vjust = 0.5,
                       color = "black", cex = lab.cex)
  }

  p
}
