#' Plot PCA Rotation
#'
#' Plot the features from a PCA rotation in a 2-dimensional scatter plot.
#' __Note:__ The precedence for the ordering of the coloring is as follows:
#'   \enumerate{
#'     \item{`col`}
#'     \item{`scores`}
#'   }
#'
#' @family PCA plots
#' @inheritParams plot_pca_dims
#' @param aptamers Optional. A vector of `SeqIds` to mark on the plot. Typically
#'   a vector of analytes related to sample handling, or of other clinical
#'   relevance. Marked with a hollow diamond (see [pch()]).
#' @param aptamers2 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   triangle (see [pch()]).
#' @param aptamers3 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   square (see [pch()]).
#' @param aptamers4 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   circle (see [pch()]).
#' @param aptamers5 Optional. An additional vector of `SeqIds` to mark
#'   on the plot, separately from those in `aptamers`. Marked with a hollow
#'   upside-down triangle (see [pch()]).
#' @param classes Optional. A vector indicating the classes of features used for
#'   coloring the points. Must be the same length as the number of features.
#' @param auto.ident Logical. Should the top 10 features, in both dimensions,
#'   be identified and labeled on the plot?
#' @param lab.cex Numeric. Font size of the point labels generated by `auto.ident`.
#'   `auto.ident` must be TRUE.
#' @param ... Additional arguments passed to [plot_pca_dims()].
#' @author Michael Mehan
#' @examples
#' feat <- grep("^seq", names(sim_adat), value = TRUE)
#' for (i in feat) sim_adat[[i]] <- log10(sim_adat[[i]])
#' pca <- center_scale(sim_adat, center = TRUE, scale = FALSE) |>
#'   strip_meta() |>
#'   prcomp2()
#' plot_rotation(pca, col = "green")
#'
#' class <- withr::with_seed(123, sample(sim_adat$class_response, 40L))
#' plot_rotation(pca, classes = class)
#'
#' apts <- withr::with_seed(123, sample(pcapkg:::get_analytes(sim_adat), 10L))
#' plot_rotation(pca, aptamers = apts)
#' @importFrom ggplot2 geom_text aes
#' @importFrom utils head tail
#' @export
plot_rotation <- function(data.prcomp, dims = 1:2L,
                          classes = NULL, scores = NULL, col = NULL,
                          aptamers = NULL, aptamers2 = NULL, aptamers3 = NULL,
                          aptamers4 = NULL, aptamers5 = NULL,
                          lab.cex = 3, pt.cex = 2.5, auto.ident = TRUE, ...) {

  if ( !is.null(aptamers) ) {
    map <- map_plot_pch(rownames(data.prcomp$rotation),
                        aptamers, aptamers2, aptamers3, aptamers4,
                        aptamers5, default.cex = pt.cex)
    pt.pch <- map$pch
    pt.cex <- map$cex
  } else {
    pt.pch <- 19
  }

  p <- plot_pca_dims(data.prcomp, dims = dims, value = "rotation",
                     classes = classes, scores = scores, col = col,
                     pt.cex = pt.cex, pt.pch = pt.pch, ...)

  if ( auto.ident ) {
    rn1 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[1L]]), ])
    rn2 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[2L]]), ])
    p1  <- c(head(rn1, 5L), tail(rn1, 5L))
    p2  <- c(head(rn2, 5L), tail(rn2, 5L))
    top <- union(p1, p2)

    # Create data subset for labeling points identified in 'top'
    labs <- p$data[top, ]
    labs$label <- ifelse(rownames(labs) %in% top,
                         gsub("^seq\\.", "", top), "")

    p <- p + geom_text(data = labs, aes(x = x, y = y, label = label),
                       hjust = -0.20, vjust = 0.5,
                       color = "black", cex = lab.cex)
  }

  p
}
