#' Plot PCA Rotation
#'
#' Plot the features from a PCA rotation in a 2-dimensional scatter plot.
#' __Note:__ The precedence for the ordering of the coloring is as follows:
#'   \enumerate{
#'     \item{`col`}
#'     \item{`scores`}
#'   }
#'
#' @family PCA plots
#' @inheritParams plot_pca_dims
#'
#' @param set1 Optional. A vector of feature ids to mark on the plot. Typically
#'   a vector of analytes of clinical relevance, e.g. sample handling.
#'   Marked with a hollow diamond (see [pch()]).
#' @param set2 Optional. An additional vector of feature ids to mark
#'   on the plot, separately from those in `set1`. Marked with a hollow
#'   triangle (see [pch()]).
#' @param set3 Optional. An additional vector of feature ids to mark
#'   on the plot, separately from those in `set1`. Marked with a hollow
#'   square (see [pch()]).
#' @param set4 Optional. An additional vector of feature ids to mark
#'   on the plot, separately from those in `set1`. Marked with a hollow
#'   circle (see [pch()]).
#' @param set5 Optional. An additional vector of feature ids to mark
#'   on the plot, separately from those in `set1`. Marked with a hollow
#'   upside-down triangle (see [pch()]).
#' @param classes Optional. A vector indicating the classes of features used for
#'   coloring the points. Must be the same length as the number of features.
#' @param auto_ident `logical(1)`. Should the top 10 features, in both dimensions,
#'   be identified and labeled on the plot?
#' @param lab_cex `numeric(1)`. Font size of the point labels generated by `auto_ident`.
#'   `auto_ident` must be TRUE.
#' @param ... Additional arguments passed to [plot_pca_dims()].
#'
#' @author Michael Mehan
#'
#' @examples
#' pca <- center_scale(pcapkg:::log_rfu(simdata), center = TRUE, scale = FALSE) |>
#'   feature_matrix() |>
#'   prcomp2()
#' plot_rotation(pca, col = "green")
#'
#' class <- withr::with_seed(123, sample(simdata$class_response, 40L))
#' plot_rotation(pca, classes = class)
#'
#' y <- withr::with_seed(123, sample(pcapkg:::get_analytes(simdata), 10L))
#' plot_rotation(pca, set1 = y)
#' @importFrom ggplot2 geom_text aes
#' @importFrom utils head tail
#' @export
plot_rotation <- function(data.prcomp, dims = 1:2L,
                          classes = NULL,
                          scores = NULL,
                          col  = NULL,
                          set1 = NULL,
                          set2 = NULL,
                          set3 = NULL,
                          set4 = NULL,
                          set5 = NULL,
                          lab_cex = 3, pt_cex = 2.5, auto_ident = TRUE, ...) {

  if ( !is.null(set1) ) {
    map <- map_plot_pch(rownames(data.prcomp$rotation),
                        set1, set2, set3, set4, set5, default_cex = pt_cex)
    pt_pch <- map$pch
    pt_cex <- map$cex
  } else {
    pt_pch <- 19
    pt_cex <- pt_cex
  }

  p <- plot_pca_dims(data.prcomp, dims = dims, value = "rotation",
                     classes = classes, scores = scores, col = col,
                     pt_cex = pt_cex, pt_pch = pt_pch, ...)

  if ( auto_ident ) {
    rn1 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[1L]]), ])
    rn2 <- rownames(data.prcomp$rotation[order(data.prcomp$rotation[, dims[2L]]), ])
    p1  <- c(head(rn1, 5L), tail(rn1, 5L))
    p2  <- c(head(rn2, 5L), tail(rn2, 5L))
    top <- union(p1, p2)

    # Create data subset for labeling points identified in 'top'
    labs <- p$data[top, ]
    labs$label <- ifelse(rownames(labs) %in% top,
                         gsub("^seq\\.", "", top), "")

    p <- p + geom_text(data = labs, aes(x = x, y = y, label = label),
                       hjust = -0.20, vjust = 0.5,
                       color = "black", cex = lab_cex)
  }

  p
}
